    // This is the source code for the JFrame.
package calculatorproject;

/**
 * David Kirk
 * Student ID: 91025041
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    Model model;
    //constructor for the frame including all the resets.
    public CalculatorFrame() {
        model = new Model();
        initComponents();
        panExtended1.setVisible(false);
        this.setLocation(350, 250);
        setSize(425,425);  
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrDegreesRadians = new javax.swing.ButtonGroup();
        bgrView = new javax.swing.ButtonGroup();
        bgrFont = new javax.swing.ButtonGroup();
        msgMessage = new javax.swing.JOptionPane();
        msgHotkeys = new javax.swing.JOptionPane();
        bgrRound = new javax.swing.ButtonGroup();
        panBasic = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnReciprocal = new javax.swing.JButton();
        btnPowerOf = new javax.swing.JButton();
        btnPositiveToNegitive = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnCleartxt = new javax.swing.JButton();
        btnRefreshtxt = new javax.swing.JButton();
        panExtended1 = new javax.swing.JPanel();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        btnAsin = new javax.swing.JButton();
        btnAcos = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        radDegrees = new javax.swing.JRadioButton();
        radRadians = new javax.swing.JRadioButton();
        mbMain = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        mnuBasicView = new javax.swing.JCheckBoxMenuItem();
        mnuExtendedView = new javax.swing.JCheckBoxMenuItem();
        mnuFont = new javax.swing.JMenu();
        mnuPlain = new javax.swing.JCheckBoxMenuItem();
        mnuBold = new javax.swing.JCheckBoxMenuItem();
        mnuRound = new javax.swing.JMenu();
        mnu0 = new javax.swing.JCheckBoxMenuItem();
        mnu1 = new javax.swing.JCheckBoxMenuItem();
        mnu2 = new javax.swing.JCheckBoxMenuItem();
        mnu3 = new javax.swing.JCheckBoxMenuItem();
        mnu4 = new javax.swing.JCheckBoxMenuItem();
        mnu5 = new javax.swing.JCheckBoxMenuItem();
        mnu6 = new javax.swing.JCheckBoxMenuItem();
        mnu7 = new javax.swing.JCheckBoxMenuItem();
        mnu8 = new javax.swing.JCheckBoxMenuItem();
        mnu9 = new javax.swing.JCheckBoxMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuHotkeys = new javax.swing.JMenuItem();
        mnuMessage = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(179, 16, 16));
        setFocusCycleRoot(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(578, 315));

        panBasic.setBackground(new java.awt.Color(179, 16, 16));
        panBasic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panBasic.setToolTipText("");
        panBasic.setPreferredSize(new java.awt.Dimension(377, 315));

        txtDisplay.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtDisplay.setText("0.0");

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(179, 16, 16));
        btn1.setMnemonic('1');
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(179, 16, 16));
        btn4.setMnemonic('4');
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(179, 16, 16));
        btn7.setMnemonic('7');
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(179, 16, 16));
        btn0.setMnemonic('0');
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(179, 16, 16));
        btn2.setMnemonic('2');
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(179, 16, 16));
        btn5.setMnemonic('5');
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(179, 16, 16));
        btn8.setMnemonic('8');
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnDecimal.setBackground(new java.awt.Color(255, 255, 255));
        btnDecimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDecimal.setForeground(new java.awt.Color(179, 16, 16));
        btnDecimal.setMnemonic('.');
        btnDecimal.setText(".");
        btnDecimal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(179, 16, 16));
        btn3.setMnemonic('3');
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(179, 16, 16));
        btn6.setMnemonic('6');
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(179, 16, 16));
        btn9.setMnemonic('9');
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnEquals.setBackground(new java.awt.Color(255, 255, 255));
        btnEquals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(179, 16, 16));
        btnEquals.setMnemonic('=');
        btnEquals.setText("=");
        btnEquals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(255, 255, 255));
        btnMulti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(179, 16, 16));
        btnMulti.setMnemonic('*');
        btnMulti.setText("*");
        btnMulti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(255, 255, 255));
        btnDivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(179, 16, 16));
        btnDivide.setMnemonic('/');
        btnDivide.setText("/");
        btnDivide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(179, 16, 16));
        btnAdd.setMnemonic('+');
        btnAdd.setText("+");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSubtract.setBackground(new java.awt.Color(255, 255, 255));
        btnSubtract.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubtract.setForeground(new java.awt.Color(179, 16, 16));
        btnSubtract.setMnemonic('-');
        btnSubtract.setText("-");
        btnSubtract.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnReciprocal.setBackground(new java.awt.Color(255, 255, 255));
        btnReciprocal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnReciprocal.setForeground(new java.awt.Color(179, 16, 16));
        btnReciprocal.setText("1/x");
        btnReciprocal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReciprocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciprocalActionPerformed(evt);
            }
        });

        btnPowerOf.setBackground(new java.awt.Color(255, 255, 255));
        btnPowerOf.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPowerOf.setForeground(new java.awt.Color(179, 16, 16));
        btnPowerOf.setText("x^n");
        btnPowerOf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPowerOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerOfActionPerformed(evt);
            }
        });

        btnPositiveToNegitive.setBackground(new java.awt.Color(255, 255, 255));
        btnPositiveToNegitive.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPositiveToNegitive.setForeground(new java.awt.Color(179, 16, 16));
        btnPositiveToNegitive.setText("+/-");
        btnPositiveToNegitive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPositiveToNegitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositiveToNegitiveActionPerformed(evt);
            }
        });

        btnFactorial.setBackground(new java.awt.Color(255, 255, 255));
        btnFactorial.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnFactorial.setForeground(new java.awt.Color(179, 16, 16));
        btnFactorial.setText("x!");
        btnFactorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnCleartxt.setBackground(new java.awt.Color(255, 255, 255));
        btnCleartxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCleartxt.setForeground(new java.awt.Color(179, 16, 16));
        btnCleartxt.setText("CA");
        btnCleartxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCleartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleartxtActionPerformed(evt);
            }
        });

        btnRefreshtxt.setBackground(new java.awt.Color(255, 255, 255));
        btnRefreshtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefreshtxt.setForeground(new java.awt.Color(179, 16, 16));
        btnRefreshtxt.setText("CE");
        btnRefreshtxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefreshtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBasicLayout = new javax.swing.GroupLayout(panBasic);
        panBasic.setLayout(panBasicLayout);
        panBasicLayout.setHorizontalGroup(
            panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBasicLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panBasicLayout.createSequentialGroup()
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReciprocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPowerOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPositiveToNegitive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panBasicLayout.createSequentialGroup()
                        .addComponent(btnCleartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panBasicLayout.setVerticalGroup(
            panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBasicLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panBasicLayout.createSequentialGroup()
                            .addComponent(btn1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn0))
                        .addGroup(panBasicLayout.createSequentialGroup()
                            .addComponent(btn2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDecimal))
                        .addGroup(panBasicLayout.createSequentialGroup()
                            .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn3)
                                .addComponent(btnMulti))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEquals)))
                    .addGroup(panBasicLayout.createSequentialGroup()
                        .addComponent(btnReciprocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPowerOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPositiveToNegitive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefreshtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCleartxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panExtended1.setBackground(new java.awt.Color(179, 16, 16));
        panExtended1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panExtended1.setAutoscrolls(true);
        panExtended1.setPreferredSize(new java.awt.Dimension(185, 315));

        btnSin.setBackground(new java.awt.Color(255, 255, 255));
        btnSin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSin.setForeground(new java.awt.Color(179, 16, 16));
        btnSin.setText("sin");
        btnSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(255, 255, 255));
        btnCos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCos.setForeground(new java.awt.Color(179, 16, 16));
        btnCos.setText("cos");
        btnCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(255, 255, 255));
        btnTan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTan.setForeground(new java.awt.Color(179, 16, 16));
        btnTan.setText("tan");
        btnTan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnPI.setBackground(new java.awt.Color(255, 255, 255));
        btnPI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPI.setForeground(new java.awt.Color(179, 16, 16));
        btnPI.setText("PI");
        btnPI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });

        btnAsin.setBackground(new java.awt.Color(255, 255, 255));
        btnAsin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAsin.setForeground(new java.awt.Color(179, 16, 16));
        btnAsin.setText("asin");
        btnAsin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsinActionPerformed(evt);
            }
        });

        btnAcos.setBackground(new java.awt.Color(255, 255, 255));
        btnAcos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAcos.setForeground(new java.awt.Color(179, 16, 16));
        btnAcos.setText("acos");
        btnAcos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcosActionPerformed(evt);
            }
        });

        btnAtan.setBackground(new java.awt.Color(255, 255, 255));
        btnAtan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtan.setForeground(new java.awt.Color(179, 16, 16));
        btnAtan.setText("atan");
        btnAtan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtanActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(255, 255, 255));
        btnE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnE.setForeground(new java.awt.Color(179, 16, 16));
        btnE.setText("E");
        btnE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        radDegrees.setBackground(new java.awt.Color(179, 16, 16));
        bgrDegreesRadians.add(radDegrees);
        radDegrees.setForeground(new java.awt.Color(255, 255, 255));
        radDegrees.setSelected(true);
        radDegrees.setText("Degrees");
        radDegrees.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDegreesItemStateChanged(evt);
            }
        });

        radRadians.setBackground(new java.awt.Color(179, 16, 16));
        bgrDegreesRadians.add(radRadians);
        radRadians.setForeground(new java.awt.Color(255, 255, 255));
        radRadians.setText("Radians");
        radRadians.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radRadiansItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panExtended1Layout = new javax.swing.GroupLayout(panExtended1);
        panExtended1.setLayout(panExtended1Layout);
        panExtended1Layout.setHorizontalGroup(
            panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtended1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtan, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(btnE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(panExtended1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(radDegrees, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(108, 108, 108))
            .addGroup(panExtended1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(radRadians, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        panExtended1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAcos, btnAsin, btnAtan, btnCos, btnE, btnPI, btnSin, btnTan});

        panExtended1Layout.setVerticalGroup(
            panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtended1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radDegrees)
                    .addComponent(radRadians))
                .addGap(35, 35, 35)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsin)
                    .addComponent(btnSin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCos)
                    .addComponent(btnAcos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTan)
                    .addComponent(btnAtan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panExtended1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPI)
                    .addComponent(btnE))
                .addGap(95, 95, 95))
        );

        panExtended1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAcos, btnAsin, btnAtan, btnCos, btnE, btnPI, btnSin, btnTan});

        mbMain.setBackground(new java.awt.Color(179, 16, 16));
        mbMain.setForeground(new java.awt.Color(255, 255, 255));

        mnuView.setForeground(new java.awt.Color(255, 255, 255));
        mnuView.setText("View");

        mnuBasicView.setBackground(new java.awt.Color(179, 16, 16));
        bgrView.add(mnuBasicView);
        mnuBasicView.setForeground(new java.awt.Color(255, 255, 255));
        mnuBasicView.setSelected(true);
        mnuBasicView.setText("Basic View");
        mnuBasicView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuBasicViewItemStateChanged(evt);
            }
        });
        mnuView.add(mnuBasicView);

        mnuExtendedView.setBackground(new java.awt.Color(179, 16, 16));
        bgrView.add(mnuExtendedView);
        mnuExtendedView.setForeground(new java.awt.Color(255, 255, 255));
        mnuExtendedView.setText("Extended View");
        mnuExtendedView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuExtendedViewItemStateChanged(evt);
            }
        });
        mnuView.add(mnuExtendedView);

        mbMain.add(mnuView);

        mnuFont.setForeground(new java.awt.Color(255, 255, 255));
        mnuFont.setText("Font");
        mnuFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFontActionPerformed(evt);
            }
        });

        mnuPlain.setBackground(new java.awt.Color(179, 16, 16));
        bgrFont.add(mnuPlain);
        mnuPlain.setForeground(new java.awt.Color(255, 255, 255));
        mnuPlain.setSelected(true);
        mnuPlain.setText("Plain");
        mnuPlain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuPlainItemStateChanged(evt);
            }
        });
        mnuFont.add(mnuPlain);

        mnuBold.setBackground(new java.awt.Color(179, 16, 16));
        bgrFont.add(mnuBold);
        mnuBold.setForeground(new java.awt.Color(255, 255, 255));
        mnuBold.setText("Bold");
        mnuBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuBoldItemStateChanged(evt);
            }
        });
        mnuFont.add(mnuBold);

        mbMain.add(mnuFont);

        mnuRound.setForeground(new java.awt.Color(255, 255, 255));
        mnuRound.setText("Round");
        mnuRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRoundActionPerformed(evt);
            }
        });

        mnu0.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu0);
        mnu0.setForeground(new java.awt.Color(255, 255, 255));
        mnu0.setText("No decimal");
        mnu0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu0ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu0);

        mnu1.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu1);
        mnu1.setForeground(new java.awt.Color(255, 255, 255));
        mnu1.setText("1 decimal");
        mnu1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu1ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu1);

        mnu2.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu2);
        mnu2.setForeground(new java.awt.Color(255, 255, 255));
        mnu2.setSelected(true);
        mnu2.setText("2 decimal");
        mnu2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu2ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu2);

        mnu3.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu3);
        mnu3.setForeground(new java.awt.Color(255, 255, 255));
        mnu3.setText("3 decimal");
        mnu3.setToolTipText("");
        mnu3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu3ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu3);

        mnu4.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu4);
        mnu4.setForeground(new java.awt.Color(255, 255, 255));
        mnu4.setText("4 decimal");
        mnu4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu4ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu4);

        mnu5.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu5);
        mnu5.setForeground(new java.awt.Color(255, 255, 255));
        mnu5.setText("5 decimal");
        mnu5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu5ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu5);

        mnu6.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu6);
        mnu6.setForeground(new java.awt.Color(255, 255, 255));
        mnu6.setText("6 decimal");
        mnu6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu6ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu6);

        mnu7.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu7);
        mnu7.setForeground(new java.awt.Color(255, 255, 255));
        mnu7.setText("7 decimal");
        mnu7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu7ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu7);

        mnu8.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu8);
        mnu8.setForeground(new java.awt.Color(255, 255, 255));
        mnu8.setText("8 decimal");
        mnu8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu8ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu8);

        mnu9.setBackground(new java.awt.Color(179, 16, 16));
        bgrRound.add(mnu9);
        mnu9.setForeground(new java.awt.Color(255, 255, 255));
        mnu9.setText("9 decimal");
        mnu9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnu9ItemStateChanged(evt);
            }
        });
        mnuRound.add(mnu9);

        mbMain.add(mnuRound);

        mnuHelp.setForeground(new java.awt.Color(255, 255, 255));
        mnuHelp.setText("Help");

        mnuHotkeys.setBackground(new java.awt.Color(179, 16, 16));
        mnuHotkeys.setForeground(new java.awt.Color(255, 255, 255));
        mnuHotkeys.setText("Hotkeys");
        mnuHotkeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotkeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotkeys);

        mnuMessage.setBackground(new java.awt.Color(179, 16, 16));
        mnuMessage.setForeground(new java.awt.Color(255, 255, 255));
        mnuMessage.setText("Message");
        mnuMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMessageActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuMessage);

        mbMain.add(mnuHelp);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panExtended1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBasic, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addComponent(panExtended1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void error(){
        String s = model.getErrorMessage();
        msgMessage.showMessageDialog
                (this, s, "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        model.reset();
        txtDisplay.setText(model.getMessage());
    }
    //Number buttons and decimal button.
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+1);
    }//GEN-LAST:event_btn1ActionPerformed
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+4);
    }//GEN-LAST:event_btn4ActionPerformed
    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+7);
    }//GEN-LAST:event_btn7ActionPerformed
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+0);
    }//GEN-LAST:event_btn0ActionPerformed
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+2);
    }//GEN-LAST:event_btn2ActionPerformed
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+5);
    }//GEN-LAST:event_btn5ActionPerformed
    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+8);
    }//GEN-LAST:event_btn8ActionPerformed
    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+".");
    }//GEN-LAST:event_btnDecimalActionPerformed
    //Decimal entry.
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+3);
    }//GEN-LAST:event_btn3ActionPerformed
    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+6);
    }//GEN-LAST:event_btn6ActionPerformed
    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+9);
    }//GEN-LAST:event_btn9ActionPerformed
    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
       
        model.setNum2(txtDisplay.getText());
        model.calculate();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }
    }//GEN-LAST:event_btnEqualsActionPerformed
    //Equals button entry. Where most of the calculations take place   
    //Calculation buttons start
    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setClear(true);
        model.setOperator(1);
    }//GEN-LAST:event_btnMultiActionPerformed
    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setClear(true);
        model.setOperator(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideActionPerformed
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setClear(true);
        model.setOperator(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed
    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setClear(true);
        model.setOperator(4);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubtractActionPerformed
    private void btnReciprocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciprocalActionPerformed
        model.setNum1(txtDisplay.getText());  
        model.setClear(true);
        model.setOperator(5);
        model.calculate();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }
    }//GEN-LAST:event_btnReciprocalActionPerformed
    private void btnPowerOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerOfActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setClear(true);
        model.setOperator(6);                                                                                // TODO add your handling code here:
    }//GEN-LAST:event_btnPowerOfActionPerformed
    private void btnPositiveToNegitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositiveToNegitiveActionPerformed
        double d = Double.parseDouble(txtDisplay.getText()); 
        txtDisplay.setText(Double.toString(d * -1));        
    }//GEN-LAST:event_btnPositiveToNegitiveActionPerformed
    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        model.setNum1(txtDisplay.getText());  
        model.setClear(true);
        model.setOperator(8);
        model.calculate();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                               // TODO add your handling code here:
    }//GEN-LAST:event_btnFactorialActionPerformed
    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        model.setClear(true);
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+Math.E);                                                // TODO add your handling code here:
    }//GEN-LAST:event_btnEActionPerformed
    private void btnAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtanActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(16);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                               // TODO add your handling code here:
    }//GEN-LAST:event_btnAtanActionPerformed
    private void btnAcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcosActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(15);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcosActionPerformed
    private void btnAsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsinActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(14);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsinActionPerformed
    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
        model.setClear(true);
        model.placeNumber(txtDisplay.getText());
        txtDisplay.setText(model.getMessage()+Math.PI);                                                                // TODO add your handling code here:
    }//GEN-LAST:event_btnPIActionPerformed
    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(13);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnTanActionPerformed
    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(12);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnCosActionPerformed
    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        model.setNum1(txtDisplay.getText());
        model.setOperator(11);
        model.calculateTrig();
        if (model.getErrorPrint() == false){
            txtDisplay.setText(model.getResult());
        }
        else{
            error();
        }                                                                                                        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinActionPerformed

    //Font menu items
private void mnuPlainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuPlainItemStateChanged
if(mnuPlain.isSelected()){
    java.awt.Font oldFont = txtDisplay.getFont();
    java.awt.Font newFont = new java.awt.Font(oldFont.getName(), java.awt.Font.PLAIN, oldFont.getSize());
    txtDisplay.setFont(newFont);
}
}//GEN-LAST:event_mnuPlainItemStateChanged
private void mnuBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuBoldItemStateChanged
if(mnuBold.isSelected()){
    java.awt.Font oldFont = txtDisplay.getFont();
    java.awt.Font newFont = new java.awt.Font(oldFont.getName(), java.awt.Font.BOLD, oldFont.getSize());
    txtDisplay.setFont(newFont);  
}
}//GEN-LAST:event_mnuBoldItemStateChanged

    //View menu items 
private void mnuBasicViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuBasicViewItemStateChanged
if(panExtended1.isVisible()){
    panExtended1.setVisible(false);
    setSize(425,425);
}
else{
    panExtended1.setVisible(true);
}
}//GEN-LAST:event_mnuBasicViewItemStateChanged
private void mnuExtendedViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuExtendedViewItemStateChanged
if(panExtended1.isVisible()){
    panExtended1.setVisible(true);
    setSize(570,425);
}
else{
    panExtended1.setVisible(false);
}
}//GEN-LAST:event_mnuExtendedViewItemStateChanged

    //Help messages
private void mnuMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMessageActionPerformed
msgMessage.showMessageDialog
        (this, "CpCalculator\r\nVersion 1.2\r\nAugust 2015\r\n\r\nCreated by David Kirk\r\nID: 91025041", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_mnuMessageActionPerformed
private void mnuHotkeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotkeysActionPerformed
msgHotkeys.showMessageDialog
        (this, "+-addition\r\n--subtraction\r\n*-multiplication\r\n/-division\r\n\r\ns-sin\r\nS-arcsin\r\nc-cos\r\nCarccos\r\nt-tan\r\nT-arctan\r\n\r\ni-inverse\r\nm-=/-\r\n^-power\r\n!-factorial\r\n\r\nd-clear all(CA)\r\nD-clear entry\r\n\r\nDigits 0-9 can be entered from the\r\nkeypad or the keyboard's digit keys.","Hotkeys" ,javax.swing.JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_mnuHotkeysActionPerformed

    //Clear and refresh textbox controlls
private void btnCleartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleartxtActionPerformed
        model.reset();
        txtDisplay.setText(model.getMessage());
}//GEN-LAST:event_btnCleartxtActionPerformed
    private void btnRefreshtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshtxtActionPerformed
        model.setMessage("0.0");
        model.setClear(true);
        txtDisplay.setText(model.getMessage());
    }//GEN-LAST:event_btnRefreshtxtActionPerformed
    //Changing font code
    private void mnuRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRoundActionPerformed
    }//GEN-LAST:event_mnuRoundActionPerformed
    private void mnuFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFontActionPerformed

    }//GEN-LAST:event_mnuFontActionPerformed
    //Rounding numbers
    private void mnu0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu0ItemStateChanged
        model.setRounder(0);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu0ItemStateChanged
    private void mnu1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu1ItemStateChanged
        model.setRounder(1);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu1ItemStateChanged
    private void mnu2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu2ItemStateChanged
        model.setRounder(2);   
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu2ItemStateChanged
    private void mnu3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu3ItemStateChanged
        model.setRounder(3);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu3ItemStateChanged
    private void mnu4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu4ItemStateChanged
        model.setRounder(4);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu4ItemStateChanged
    private void mnu5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu5ItemStateChanged
        model.setRounder(5);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu5ItemStateChanged
    private void mnu6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu6ItemStateChanged
        model.setRounder(6);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu6ItemStateChanged
    private void mnu7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu7ItemStateChanged
        model.setRounder(7);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu7ItemStateChanged
    private void mnu8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu8ItemStateChanged
        model.setRounder(8);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu8ItemStateChanged
    private void mnu9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnu9ItemStateChanged
        model.setRounder(9);
        model.round(Double.parseDouble(txtDisplay.getText()));
        txtDisplay.setText(model.getResult());
    }//GEN-LAST:event_mnu9ItemStateChanged
    //Radians and degrees radio buttons code
    private void radDegreesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDegreesItemStateChanged
        if (radDegrees.isSelected()){
            model.setRadians(false);
        }
        else{
            model.setRadians(true);
        }
    }//GEN-LAST:event_radDegreesItemStateChanged
    private void radRadiansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radRadiansItemStateChanged
        if (radRadians.isSelected()){
            model.setRadians(true);
        }
        else{
            model.setRadians(false);
        }       
    }//GEN-LAST:event_radRadiansItemStateChanged
         
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrDegreesRadians;
    private javax.swing.ButtonGroup bgrFont;
    private javax.swing.ButtonGroup bgrRound;
    private javax.swing.ButtonGroup bgrView;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcos;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAsin;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnCleartxt;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPositiveToNegitive;
    private javax.swing.JButton btnPowerOf;
    private javax.swing.JButton btnReciprocal;
    private javax.swing.JButton btnRefreshtxt;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btnTan;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JCheckBoxMenuItem mnu0;
    private javax.swing.JCheckBoxMenuItem mnu1;
    private javax.swing.JCheckBoxMenuItem mnu2;
    private javax.swing.JCheckBoxMenuItem mnu3;
    private javax.swing.JCheckBoxMenuItem mnu4;
    private javax.swing.JCheckBoxMenuItem mnu5;
    private javax.swing.JCheckBoxMenuItem mnu6;
    private javax.swing.JCheckBoxMenuItem mnu7;
    private javax.swing.JCheckBoxMenuItem mnu8;
    private javax.swing.JCheckBoxMenuItem mnu9;
    private javax.swing.JCheckBoxMenuItem mnuBasicView;
    private javax.swing.JCheckBoxMenuItem mnuBold;
    private javax.swing.JCheckBoxMenuItem mnuExtendedView;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotkeys;
    private javax.swing.JMenuItem mnuMessage;
    private javax.swing.JCheckBoxMenuItem mnuPlain;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JMenu mnuView;
    private javax.swing.JOptionPane msgHotkeys;
    public javax.swing.JOptionPane msgMessage;
    private javax.swing.JPanel panBasic;
    private javax.swing.JPanel panExtended1;
    private javax.swing.JRadioButton radDegrees;
    private javax.swing.JRadioButton radRadians;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
